module "bastion" {
  source  = "Azure/avm-res-network-bastionhost/azurerm"
  version = "0.9.0"

  count = local.deploy_bastion ? 1 : 0

  name      = local.names.bastion
  location  = local.location
  parent_id = module.resource_group_connectivity.resource_id
  tags      = local.tags

  sku = "Basic"

  ip_configuration = {
    name                   = "ipconfig-default"
    subnet_id              = module.hub_virtual_network.subnets["bastion"].resource_id
    create_public_ip       = true
    public_ip_address_name = local.names.bastion_public_ip
  }
}

module "jumpbox" {
  source  = "Azure/avm-res-compute-virtualmachine/azurerm"
  version = "0.21.0"

  count = local.deploy_bastion ? 1 : 0

  name                = local.names.jumpbox
  location            = local.location
  resource_group_name = module.resource_group_connectivity.name
  enable_telemetry    = local.enable_telemetry
  tags                = local.tags

  os_type  = "Linux"
  sku_size = local.jumpbox_size
  zone     = 1

  source_image_reference = {
    publisher = "Canonical"
    offer     = "ubuntu-24_04-lts"
    sku       = "server"
    version   = "latest"
  }

  os_disk = {
    caching              = "ReadWrite"
    storage_account_type = "Premium_LRS"
  }

  network_interfaces = {
    primary = {
      name = local.names.jumpbox_nic
      ip_configurations = {
        primary = {
          name                          = "ipconfig-primary"
          private_ip_subnet_resource_id = module.hub_virtual_network.subnets["management"].resource_id
        }
      }
    }
  }

  managed_identities = {
    system_assigned = true
  }

  # An SSH key pair is generated by the module and exposed through its outputs.
  account_credentials = {
    admin_credentials = {
      username = "azureuser"
    }
  }

  custom_data = base64encode(<<-CLOUDINIT
    #cloud-config
    package_update: true
    runcmd:
      - curl -sL https://aka.ms/InstallAzureCLIDeb | bash
      - az aks install-cli
  CLOUDINIT
  )
}
